Homework 9
max-zamkovoy/MadeAlgorithmsAndDataStructures pull request #7
Opened 2020-01-04 10:29 UTC by max-zamkovoy

18_1: https://contest.yandex.ru/contest/16362/run-report/29357943/
19: https://contest.yandex.ru/contest/16362/run-report/29331365/

2020-01-04 10:31 UTC, max-zamkovoy commented
@ylyubimov прошу проверить оба задания. В 18_1 не удалось пройти 47 тест. Подскажите, пожалуйста, как его можно было бы пройти.

2020-01-08 13:36 UTC, ylyubimov requested changes
18 - пока есть, что сделть симпатичнее. Питон в 100 раз требовательнее к стилю и оформлению, чем C++, потому что язык нетипизированный, поэтому разобраться в коде сильно сложнее.
Тест просто не проходит по памяти на 90000 точек(float) ~ 360Kb ты съел сильно больше 15Mb  памяти. Возможно что-то не так с твоей сортировкой.
19 - это не геохеш

2020-01-08 13:36 UTC, ylyubimov commented on HomeWork9/18_1.py
> +    if val == 0:
Вряд ли у тебя даже в питоне получится полный ноль, если с ты работаешь с float'ом

2020-01-08 13:36 UTC, ylyubimov commented on HomeWork9/18_1.py
> +    if points[i][1] < point_0[1] or (points[i][1] == point_0[1] and points[i][0] < point_0[0]):
Уверен, что в питоне есть метод для выбора минимума с лямда-функцией сравнения

2020-01-08 13:36 UTC, ylyubimov commented on HomeWork9/18_1.py
> +    print(summ)
Нет разбиения на функции. Нужна функция подсчета периметра. Функция построения выпуклой оболочки.

2020-01-08 13:36 UTC, ylyubimov commented on HomeWork9/18_1.py
> +    if pointer >= len_p - 1:
Зачем еще один счетчик, если он всегда прибавляется +1 как и i?

2020-01-08 13:36 UTC, ylyubimov commented on HomeWork9/19.py
> +	print(res[i])
Кажется, это полный поиск, а не геохеш

2020-01-10 07:23 UTC, max-zamkovoy commented on HomeWork9/18_1.py
> +    if points[i][1] < point_0[1] or (points[i][1] == point_0[1] and points[i][0] < point_0[0]):
Зачем отдельно искать минимум, проходя по списку точек еще раз, если можно по мере чтения смотреть? Не очень понятно зачем для этого нужна лямбда.

2020-01-10 07:24 UTC, max-zamkovoy commented on HomeWork9/18_1.py
> +    if val == 0:
Исправлено.

2020-01-10 07:24 UTC, max-zamkovoy commented on HomeWork9/18_1.py
> +    print(summ)
Исправлено.

2020-01-10 07:24 UTC, max-zamkovoy commented on HomeWork9/18_1.py
> +    if pointer >= len_p - 1:
Исправлено.

2020-01-13 05:25 UTC, max-zamkovoy commented on HomeWork9/19.py
> +	print(res[i])
Переделал на C++ в https://github.com/max-zamkovoy/MadeAlgorithmsAndDataStructures/commit/83673d8a3d192061879ee4b743588fe4b044bb23
Прошу перепроверить.

2020-01-13 21:29 UTC, ylyubimov commented on HomeWork9/18_1.py
> +    if points[i][1] < point_0[1] or (points[i][1] == point_0[1] and points[i][0] < point_0[0]):
Просто я подумал, что ты уже считал все строчки. В общем, в курсе обговаривалось, что вы будете писать методы таким образом, чтобы не смешивать ввод/вывод и алгоритм, потому что алгоритм не обязательно работает с вводом/выводом. У меня уже может быть массив точек.

2020-01-13 21:32 UTC, ylyubimov commented
Ты 19 в контест посылал?

2020-01-13 21:34 UTC, ylyubimov reviewed
18 зачел. Жду 19 с контестом.

2020-01-13 21:34 UTC, ylyubimov commented on HomeWork9/18_1.py
> +def quicksort(A, lo = None, hi = None):
Сортировку, конечно, тут свою писать не надо было)

2020-01-13 21:34 UTC, ylyubimov commented on HomeWork9/18_1.py
> +import numpy as np
numpy мы вроде договаривались не использовать)

2020-01-14 03:51 UTC, max-zamkovoy commented
@ylyubimov да, 19 в контест посылал: https://contest.yandex.ru/contest/16362/run-report/29718482/

2020-01-14 03:53 UTC, max-zamkovoy commented
> Ты 19 в контест посылал?

2020-01-14 03:53 UTC, closed without merging

2020-01-14 21:18 UTC, ylyubimov commented
19 тоже поставил